[default]
src = 'src'
out = 'out'
libs = ['lib']
# solc = "0.8.10" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"` --> if commented out will auto detect
cache = true
cache_path = 'cache'
optimization = true
optimizer_runs = 2000
etherscan_api_key="YOURETHERSCANAPIKEY"
remappings = [
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@arcadexyz/=lib/v2-contracts/contracts/"
]


[default.rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/FOUNDRY_ALCHEMY_API_KEY"
goerli = "https://eth-goerli.g.alchemy.com/v2/FOUNDRY_ALCHEMY_API_KEY"

# See more config options https://github.com/gakonst/foundry/tree/master/config
